DROP DATABASE IF EXISTS trykedb;
CREATE DATABASE trykedb;

DROP DATABASE IF EXISTS userdb;
CREATE DATABASE userdb;

CREATE TABLE posts(
id int AUTO_INCREMENT,
title VARCHAR (200),
address VARCHAR (200),
zip VARCHAR (200),
body VARCHAR (500),
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
PRIMARY KEY(id)
);

CREATE TABLE users(
id int AUTO_INCREMENT,
name VARCHAR (200),
password VARCHAR (200),
email VARCHAR (200),
zip VARCHAR (200),
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL DEFAULT NOW() ON UPDATE NOW(),
PRIMARY KEY(id)
);